# QUITA version (obsoleto)
services:
  agrosync-api:
    build: .
    ports:
      - "8282:8282"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
